apiVersion: v1
#apiVersion: apps/v1alpha1
#kind: PetSet
kind: ReplicationController
metadata:
   name: mariadb-{{count}}
   namespace: "default"
spec:
#  serviceName: "galera"
  replicas: 1
  selector:
    service: mariadb-{{count}}
  template:
    metadata:
      labels:
        service: mariadb-{{count}}
#      annotations:
#        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        kubernetes.io/hostname: 172.16.35.13
      containers:
        - image: "{{container_name}}"
          name: main
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
            - mountPath: /var/log/mariadb
              name: mariadb-persistent-storage
            - mountPath: /etc/nave
              name: mariadb-config
          ports:
            - containerPort: 3306
              name: mariadb-{{count}}
            - containerPort: 4444
              name: sst
            - containerPort: 4567
              name: replication
            - containerPort: 4568
              name: ist
          env:
            - name: BOOTSTRAP_ARGS
              value: {{bootstrap_args}}
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-{{count}}
        - name: mariadb-config
          configMap:
            name: mariadb-{{count}}
