apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-{{count}}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/lib/kolla/volumes/mariadb-{{count}}
